### ISSUE TITLE
AsyncFnOnce not found in this scope

### ISSUE THREAD

**Issue by sh2ezo** [mdeloof/statig#71]
Hello!

Thank you for your effort with this library.

Tried to use 'async' feature on version 0.4.1 and got the following error on compile:

```
error[E0405]: cannot find trait `AsyncFnOnce` in this scope
   --> C:\Users\svobo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\statig-0.4.1\src\awaitable\into_state_machine.rs:152:8
    |
152 |     F: AsyncFnOnce(&mut T, &T::State, &T::State, &mut T::Context<'_>),
    |        ^^^^^^^^^^^ not found in this scope
    |
help: consider importing this trait
    |
1   + use core::ops::AsyncFnOnce;
    |
```

Downgrade to 0.4.0 doesn't help

**Comment by mdeloof** [comment]
What version of version of rust are you using? I just saw that `AsyncFnOnce` was stabilised in 1.85, so I'll probably will need to bump minimum supported rust version to that.

**Comment by sh2ezo** [comment]
Hello! After upgrade to 1.88 this issue is gone. Thanks
